# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auto

on:
  push:
    tags: 
      - "v*"
  pull_request:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dep
      run: npm ci
    - name: Install Nexe
      run: npm -g install nexe
    - name: Build executable for mac x64
      run: nexe bn.js -t macos-x64-${{ matrix.node-version }} -o macos/bn${{ github.ref_name }}_macos
    - name: Build exeutable for windows x64
      run: nexe bn.js -t windows-x64-${{ matrix.node-version }} -o windows/bn${{ github.ref_name }}_windows.exe
    - name: Build executable for linux x64
      run: nexe bn.js -t linux-x64-${{ matrix.node-version }} -o linux/bn${{ github.ref_name }}_linux
    - name: Auto release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          macos/bn${{ github.ref_name }}_macos
          windows/bnbn${{ github.ref_name }}_windows.exe
          linux/bn${{ github.ref_name }}_linux
