# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auto

on:
  push:
    branches: 
      - main
      - release/*
    tags: 
      - "v*"
  pull_request:
    branches: 
      - main
      - release/*
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dep
      run: npm ci
    - name: Install Nexe
      run: npm -g install nexe
    - name: Build executable for mac 
      run: nexe bn.js -t macos-x64-${{ matrix.node-version }} -o macos-x64-bn-nodejs${{ matrix.node-version }}
    - name: Build exeutable for windows
      run: nexe bn.js -t windows-x64-${{ matrix.node-version }} -o windows-x64-bn-nodejs${{ matrix.node-version }}
    - name: Build executable for linux
      run: nexe bn.js -t linux-x64-${{ matrix.node-version }} -o linux-x64-bn-nodejs${{ matrix.node-version }}
    - name: Auto release
      uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref_name == "v*"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          macos-x64-bn-nodejs${{ matrix.node-version }}
          windows-x64-bn-nodejs${{ matrix.node-version }}
          linux-x64-bn-nodejs${{ matrix.node-version }}
